
# Site wide configuration

title: Andrew F. Hart
description: "Personal website of Andrew F. Hart."
logo: site-logo.png
teaser: default-teaser.png
locale: en_US
url: 


# Jekyll configuration

permalink: /:categories/:title/
lsi: true
markdown: kramdown
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap
  - jekyll-archives
include: [".htaccess"]
exclude: ["vendor", "skinny-bones", "lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "node_modules", "Gruntfile.js", "package.json", ".jekyll-assets-cache"]


# Plugin: jekyll-assets

assets:
  sources:
    - _assets/javascripts
    - _assets/stylesheets
  js_compressor: uglifier
  css_compressor: sass
  cachebust: hard
  cache: true
  debug: false
  version: 1


# Plugin: jekyll-archives

jekyll-archives:
  enabled:
    - tags
    - year
  layouts:
    year: year_index
    tag: tag_index
  permalinks:
    year: /:year/
    tag: /tag/:name/


# Site owner

owner:
  name: Andrew Hart
  email: hello@andrewfhart.com
  twitter: andrewfhart
  facebook: andrewfhart
  instagram: andrewfhart
  tumblr: andrewfhart
  google:
    ad-client: 
    ad-slot: 
    analytics: 
    plus:
    verify:
  bing:
    verify: 
  alexa:
    verify: 
  yandex:
    verify: 
  bio: "Software Engineer, Entrepreneur, Photographer, Dreamer"
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: 


# Collections

collections:
  faqs:
    output: true
    permalink: /:collection/:path/
    title: FAQs
